-- Add comprehensive evidence packets from Final_Apes_Doc

-- DENIER EVIDENCE
INSERT INTO public.evidence_packets (title, source, source_url, evidence_type, summary, key_claim, supports, caveats, tags, difficulty, snippet) VALUES
('Global Temperature Rise - Six Independent Datasets', 'Multiple sources (HadCRUT, NOAA, Berkeley Earth, NASA GISTEMP, Japan Met JRA-55, ECMWF ERA5)', 'https://climate.nasa.gov/vital-signs/global-temperature/', 'graph', 'Six independent global temperature datasets all demonstrate consistent rise in global average temperature from 1850 to present', 'Global average temperature has risen approximately 1°C since pre-industrial times, with all six independent datasets showing consistent trends', ARRAY['Temperature is measurably rising', 'Multiple independent data sources confirm the trend', 'Scientific consensus on warming'], ARRAY['Different datasets use different baselines', 'Measurement methods have evolved over time'], ARRAY['temperature', 'trend', 'observational', 'consensus'], 'Easy', 'Six independent datasets (HadCRUT 1850-, NOAA 1850-, Berkeley Earth 1850-, NASA GISTEMP 1880-, Japan Met JRA-55 1958-, ECMWF ERA5 1979-) all show consistent warming trend'),

('US 30-Year Temperature Normals', 'NOAA Climate.gov / NCEI', 'https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals', 'graph', 'Shows how U.S. annual temperatures compared to 20th-century average have consistently increased across successive 30-year climate normal periods', 'Climate normals (30-year periods) show progressive warming, demonstrating climate change vs weather fluctuation', ARRAY['Climate measured in 30-year intervals', 'Recent periods warmer than historical baseline', 'Distinguishes climate from weather'], ARRAY['Baselines are updated over time', 'Regional variations exist'], ARRAY['temperature', 'climate normals', 'US data', 'observational'], 'Moderate', 'Each successive 30-year normal period (1901-1930 through 1991-2020) shows increasing temperature deviation from 20th century average'),

('Mauna Loa CO₂ Concentration Record', 'Scripps Oceanography / UC San Diego', 'https://scrippsco2.ucsd.edu/data/atmospheric_co2/primary_mlo_co2_record.html', 'graph', 'The longest continuous record of atmospheric CO₂ measurements, showing steady increase from ~315 ppm in 1958 to over 420 ppm in 2024', 'Atmospheric CO₂ has increased by over 100 ppm since systematic measurements began, rising from ~315 ppm to over 420 ppm', ARRAY['CO₂ is measurably increasing', 'Trend is consistent and accelerating', 'Human timescale observation'], ARRAY['Single location measurement (though representative)', 'Seasonal variations visible'], ARRAY['CO2', 'Mauna Loa', 'observational', 'long-term'], 'Easy', 'Continuous measurements from 1958 to 2024 show CO₂ rising from 315 ppm to 420+ ppm'),

('800,000 Year CO₂ Ice Core Record', 'Antarctic ice core data', 'https://www.ncei.noaa.gov/products/paleoclimatology/ice-core', 'graph', 'Ice core data spanning 800,000 years shows CO₂ levels remained between 150-300 ppm until recent dramatic spike to 420+ ppm', 'Current CO₂ levels (420+ ppm) are unprecedented in at least 800,000 years, far exceeding natural variability (150-300 ppm)', ARRAY['Current CO₂ levels are unprecedented', 'Natural range was 150-300 ppm for 800,000 years', 'Recent spike is anomalous'], ARRAY['Ice core dating has uncertainty margins', 'Proxy measurements vs direct'], ARRAY['CO2', 'ice cores', 'paleoclimate', 'long-term'], 'Moderate', 'For 800,000 years CO₂ stayed between 150-300 ppm, but has spiked to 420+ ppm in last 250 years'),

-- DOUBTER EVIDENCE
('Climate Forcing Factors Analysis', 'IPCC / Climate modeling studies', 'https://www.ipcc.ch/', 'graph', 'Comprehensive analysis showing temperature changes correlate with greenhouse gases and human factors, not with natural factors alone (solar, volcanic, orbital)', 'When all factors are analyzed, only greenhouse gases and human activities match observed temperature rise; natural factors alone do not explain the trend', ARRAY['Natural factors insufficient to explain warming', 'Greenhouse gases match observed trend', 'Human factors correlate with temperature'], ARRAY['Model uncertainties exist', 'Multiple variables interacting'], ARRAY['climate models', 'attribution', 'confounding variables', 'greenhouse gases'], 'Hard', 'Observed temperature follows GHG and human factors trend, not natural factors (solar, volcanic, orbital) alone'),

('Carbon Isotope Analysis (¹³C)', 'Ice core and atmospheric measurements', 'https://www.esrl.noaa.gov/gmd/ccgg/isotopes/', 'graph', 'Ratio of ¹³C isotope in atmosphere shows decline starting around 1850, matching fossil fuel carbon signature', 'The isotopic signature of atmospheric carbon shows it originates from fossil fuels, not natural sources', ARRAY['Can distinguish human vs natural CO₂', 'Fossil fuel signature is detectable', 'Timing matches industrial era'], ARRAY['Requires understanding of isotope chemistry', 'Multiple carbon sources in system'], ARRAY['isotopes', 'carbon-13', 'attribution', 'fossil fuels'], 'Extreme', '¹³C/¹²C ratio declined sharply after 1850, indicating fossil fuel origin of added CO₂'),

('Carbon-14 Depletion', 'Atmospheric ¹⁴C measurements', 'https://www.esrl.noaa.gov/gmd/ccgg/isotopes/', 'graph', '¹⁴C concentration in atmosphere has decreased due to burning of ancient fossil fuels that lack ¹⁴C', 'Declining ¹⁴C proves added CO₂ comes from ancient fossil sources, not modern biological activity', ARRAY['Fossil fuels are ¹⁴C-depleted', 'Atmospheric ¹⁴C declining as predicted', 'Confirms human source'], ARRAY['Nuclear testing affected ¹⁴C levels', 'Complex carbon cycle interactions'], ARRAY['isotopes', 'carbon-14', 'attribution', 'fossil fuels'], 'Extreme', '¹⁴C in atmosphere decreased 1700-1950 as fossil fuel burning added ancient carbon'),

('Antarctic Temperature and CO₂ Correlation (800kyr)', 'Ice core data', 'https://www.ncei.noaa.gov/products/paleoclimatology/ice-core', 'graph', 'Shows strong correlation between CO₂ and temperature over 800,000 years, with current levels far exceeding natural range', 'CO₂ and temperature are tightly coupled; current CO₂ spike predicts temperature rise', ARRAY['CO₂ and temperature correlate', 'Natural cycles visible', 'Current spike is unprecedented'], ARRAY['Correlation does not prove causation alone', 'Lag times between CO₂ and temp exist'], ARRAY['CO2', 'temperature', 'correlation', 'ice cores', 'paleoclimate'], 'Hard', '800,000 years of data show CO₂ varying 150-300 ppm with temperature; current 420 ppm is off the chart'),

-- NAIVE EVIDENCE  
('Flood Mortality by Income Level', 'Global flood impact studies', 'https://www.worldbank.org/en/topic/disasterriskmanagement', 'graph', 'Climate change-induced flooding causes mortality across ALL wealth levels, including high-income regions', 'Even wealthy populations suffer losses and mortality from climate impacts; no one is immune', ARRAY['All income levels affected', 'High income not complete protection', 'Global impact'], ARRAY['Data aggregation may mask local variations', 'Multiple factors influence mortality'], ARRAY['flooding', 'mortality', 'socioeconomic', 'impacts'], 'Moderate', 'High-income regions still show 0.3%+ mortality from flooding; low-income areas even higher'),

('Projected Economic Damage by Income Bracket (US Counties)', 'Hsiang, Kopp, Jina, Rising, et al. (2017)', 'https://science.sciencemag.org/content/356/6345/1362', 'graph', 'Economic projections show climate damage will hit all income brackets, with poorest facing up to 20% GDP loss and richest still facing 5%+ loss', 'Climate change will cause economic damage across all income levels; even the wealthy will lose 5%+ of GDP', ARRAY['All economic groups will suffer losses', 'Poorest hit hardest but rich not immune', 'Quantified economic impacts'], ARRAY['Projections have uncertainty ranges', 'Based on specific emission scenarios'], ARRAY['economics', 'GDP loss', 'inequality', 'projections'], 'Moderate', 'Richest 10% face ~5% GDP loss, poorest 10% face up to 20% loss from climate impacts'),

('Heat-Related Mortality Trends', 'Public health data', 'https://www.who.int/health-topics/climate-change', 'graph', 'Death rates from heat exposure show clear upward trend from 1970-2006, with linear relationships across income and population weighting', 'Heat-related deaths are already rising and will continue to increase with warming', ARRAY['Measurable mortality increase', 'Trend is established', 'Multiple metrics show same pattern'], ARRAY['Data collection methods vary', 'Attribution can be complex'], ARRAY['mortality', 'heat', 'health impacts', 'trend'], 'Easy', 'Linear increase in heat deaths from 1970-2006, r²=0.44 income-weighted, r²=0.58 population-weighted'),

('Heat Capacity and 1°C Significance', 'Physics principles / NASA', 'https://climate.nasa.gov/', 'explanation', '1°C change in ocean temperature represents enormous energy transfer due to water''s high heat capacity; can cause massive heatwaves and weather disruptions', 'Even small temperature changes represent huge energy shifts that drive extreme weather', ARRAY['1°C is physically significant', 'Ocean heat capacity is enormous', 'Energy drives weather extremes'], ARRAY['Requires understanding of thermodynamics', 'Local vs global temperature'], ARRAY['heat capacity', 'oceans', 'energy', 'physics'], 'Hard', '1°C change in large water body requires massive energy, causing heatwaves and extreme weather'),

-- CYNIC EVIDENCE
('Temperature Overshoot Scenarios', 'IPCC climate models', 'https://www.ipcc.ch/sr15/', 'graph', 'Models show that with rapid decarbonization starting now, temperature would stabilize and could decline; shows it is NOT too late', 'Rapid decarbonization can stabilize and reduce temperatures; meaningful change is still possible', ARRAY['Action can limit warming', 'Not too late for impact', 'Overshoot can be reversed'], ARRAY['Requires unprecedented action', 'Political will uncertain'], ARRAY['mitigation', 'scenarios', 'decarbonization', 'hope'], 'Moderate', 'Rapid decarbonization scenario shows temperature flattening after emissions peak, proving action matters'),

('American Climate Corps Initiative', 'Biden Administration (2023)', 'https://www.whitehouse.gov/briefing-room/', 'policy', 'Tens of thousands of young Americans dedicating careers to climate work through the American Climate Corps program', 'Large-scale climate action is already mobilizing; people are NOT giving up', ARRAY['Concrete action being taken', 'Youth engagement high', 'Career pathways created'], ARRAY['Program recently launched', 'Long-term impact TBD'], ARRAY['policy', 'action', 'youth', 'careers'], 'Easy', 'Tens of thousands enrolling in Climate Corps to repair climate, showing active engagement not resignation'),

('Climate Clock', 'Climate Clock project based on IPCC data', 'https://climateclock.world/', 'data visualization', 'Calculates remaining time before 1.5°C threshold (Paris Agreement target) is reached based on current carbon budget and emission rates', 'We have approximately 3 years at current rates to stay under 1.5°C; urgency is real but action window exists', ARRAY['Quantifies urgency', 'Based on carbon budget science', 'Time-bound target'], ARRAY['Depends on emission trajectories', 'Target is policy choice'], ARRAY['carbon budget', 'Paris Agreement', 'urgency', '1.5C'], 'Moderate', 'Climate Clock shows ~3 years remaining to 1.5°C if emissions continue; small window for action'),

('Greenhouse Gas Absorption Spectrum & Technology Report', 'IPCC 2022 Report', 'https://www.ipcc.ch/report/ar6/', 'report + graph', 'Detailed absorption spectra of greenhouse gases plus comprehensive review of mitigation technologies, policies and pledges', 'Technology exists, mechanisms are understood, and many governments have plans; we have tech and plan', ARRAY['Technology is available', 'Science is well understood', 'Policy frameworks exist'], ARRAY['Implementation gaps remain', 'Political will varies'], ARRAY['technology', 'policy', 'mitigation', 'absorption spectrum'], 'Hard', '2022 IPCC report documents existing technology and government pledges; absorption spectra prove CO₂ mechanism'),

('Inaction vs Action Economic Analysis', 'Economic modeling studies', 'https://www.lse.ac.uk/granthaminstitute/', 'analysis', 'Economic analysis showing that inaction on climate will cost MORE than action; climate damages exceed mitigation costs', 'Acting on climate is economically rational; inaction will cost more in damages than mitigation would cost', ARRAY['Economics favor action', 'Inaction has higher costs', 'Investment now prevents losses'], ARRAY['Cost estimates have ranges', 'Discount rates debated'], ARRAY['economics', 'cost-benefit', 'mitigation', 'damages'], 'Moderate', 'Projected damage (5-20% GDP loss) exceeds cost of climate action; economy cannot afford inaction'),

-- ZEALOT EVIDENCE
('Six Americas Climate Opinion Tracking (2012-2022)', 'Yale Program on Climate Change Communication', 'https://climatecommunication.yale.edu/about/projects/global-warmings-six-americas/', 'survey data', 'Longitudinal survey showing Alarmed segment grew from 12% to 26% (2012-2022), while Cautious dropped from 29% to 17%', 'More people are alarmed about climate, but significant portions remain cautious, doubtful or dismissive; facts alone do not always motivate action', ARRAY['Public awareness is growing', 'Alarmed segment doubled', 'Majority concerned or alarmed'], ARRAY['Self-reported beliefs', 'US-focused data', 'Behavior vs belief gap'], ARRAY['public opinion', 'communication', 'psychology', 'surveys'], 'Moderate', '26% alarmed + 27% concerned = 53% in 2022, but action gap persists despite awareness'),

('Hope vs Fear in Climate Communication', 'Communication research', 'https://www.apa.org/science/about/psa/2017/11/climate-change', 'research summary', 'Research shows that fear can paralyze rather than motivate; solution-focused messaging creates hope and drives action', 'Fear-based messaging can backfire; educating about solutions is more effective than spreading fear', ARRAY['Psychology of climate communication', 'Hope drives action', 'Fear can paralyze'], ARRAY['Context-dependent effects', 'Audience variability'], ARRAY['communication', 'psychology', 'fear', 'hope', 'messaging'], 'Hard', 'Fear of rising heat deaths can paralyze; teaching solutions and creating hope drives effective action');